name: Create Release Pull Request

on:
  push:
    branches:
      - 'release/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - run: yarn install --frozen-lockfile

      - name: Setup Git identity
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Release PR
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}